# Generated by Django 4.1.3 on 2022-11-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crutch',
            name='datePublished',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crutch',
            name='imageField',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
